
import React, { useState } from 'react';
import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'
import { nanoid } from 'nanoid'
export default function Home() {


  const [todos, setTodos] = useState([]);
  const [name, setName] = useState("");
  let handleClick = (e) => {
    e.preventDefault();
    setTodos([...todos, { id: nanoid(), todo: name }])

  }

  let handleChange = (e) => {
    setName(e.target.value);
  }

  let deleteTodo = (key) => {
    const remainingTask = todos.filter(todo => todo.id !== key)
    setTodos(remainingTask);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Todo List!!</h1>
        <div className={styles.inputTodo}>
          <input
            type="text"
            name="text"
            autoComplete="off"
            value={name}
            onChange={handleChange}
          />
          <button onClick={handleClick}>Add</button>
        </div>
        <div>
          {
            todos.map((todo) => (
              <Card key={todo.id} id={todo.id} todo={todo.todo} deleteTodo={deleteTodo} />
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
