
import React, { useState } from 'react';
import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'
import { nanoid } from 'nanoid'
export default function Home() {


  const [todos, setTodos] = useState([]);
  const [name, setName] = useState("");
  let handleClick = (e) => {
    // let val = e.target.value
    // setInputVal(val);
    // console.log()
    e.preventDefault();
    setTodos([...todos, name]);

  }

  let handleChange = (e) => {
    // const inputvalue=e.target.value;
    setName(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Todo List!!</h1>
        <div className={styles.inputTodo}>
          <input
            type="text"
            name="text"
            autoComplete="off"
            value={name}
            onChange={handleChange}
          />
          <button onClick={handleClick}>Add</button>
        </div>
        <div>
          {
            todos.map((todo, index) => (

              <Card key={index} todo={todo} />
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
